apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: generate-artifact-manifest
description: Generates a YAML manifest of latest artifacts for a list of components.

inputs:
  cb_api_url:
    required: true
  cb_pat:
    required: true
  component_ids:
    required: true
    description: Comma-separated list of component IDs (e.g. id1,id2)
  labels:
    required: true
    description: Label filters to apply (e.g. rel=squid-ui,ns=squid-prod)
  org_id:
    required: false
    description: Optional organization ID for org-scoped component lookups

outputs:
  manifest:
    description: YAML-formatted artifact manifest with IDs, versions, timestamps, artifact names, component names, and match status
    value: ${{ steps.generate.outputs.manifest }}
  errors:
    description: JSON-formatted list of components that failed to fetch or match (and non-fatal name-lookup notes)
    value: ${{ steps.generate.outputs.errors }}

runs:
  using: composite
  steps:
    - id: generate
      name: Generate artifact manifest
      uses: docker://python:3.11-alpine
      shell: sh
      env:
        CB_API_URL: ${{ inputs.cb_api_url }}
        CB_PAT: ${{ inputs.cb_pat }}
        COMPONENT_IDS: ${{ inputs.component_ids }}
        LABELS: ${{ inputs.labels }}
        ORG_ID: ${{ inputs.org_id }}
      run: |
        set -euo pipefail
        apk add --no-cache curl jq yq > /dev/null

        echo "🔍 Fetching latest artifacts for: $COMPONENT_IDS"
        : > manifest.yaml
        echo '{"errors":[]}' > errors.json
        mkdir -p .cache
        echo "🔍 Created blank manifest, error file, and cache dir"

        # Build a jq filter that tolerates missing labels:
        FILTER=$(echo "$LABELS" | awk -F, '
          BEGIN { first=1 }
          {
            for (i = 1; i <= NF; i++) {
              if ($i == "") continue
              split($i, kv, "=")
              if (!first) { printf " and " }
              printf "(((.labels // []) | index(\"%s=%s\")))", kv[1], kv[2]
              first=0
            }
          }')

        if [ -z "$FILTER" ]; then
          echo "ℹ️  No labels provided after parsing; defaulting to match-any artifact"
          FILTER="true"
        fi

        echo "🔍 Filtering artifacts by labels: $LABELS"
        echo "🧮 Using jq filter: $FILTER"

        # ---- helper: try to read a component name from a JSON file using multiple common locations
        _extract_name_from_json () {
          jq -r '
            .component.name
            // .component.displayName
            // .component.title
            // .name
            // .displayName
            // .title
            // .metadata.name
            // .data.name
            // empty
          ' "$1" 2>/dev/null || true
        }

        # ---- helper: name lookup with caching. Tries (1) artifactinfos body, (2) /v3/components/{id},
        # ---- and (3) /v3/organizations/{orgId}/components/{id} if org_id is provided.
        get_component_name () {
          _id="$1"

          # cache hit?
          if [ -f ".cache/${_id}.name" ]; then
            cat ".cache/${_id}.name"
            return 0
          fi

          # 1) Try the current artifactinfos body if present
          local n=""
          if [ -f response.json ]; then
            n="$(_extract_name_from_json response.json)"
          fi

          # 2) Try global component endpoint
          local s1="0"
          if [ -z "${n:-}" ]; then
            s1=$(curl -s -w "%{http_code}" -o comp.json \
              -H "Authorization: Bearer $CB_PAT" \
              -H "Accept: application/json" \
              "$CB_API_URL/v3/components/${_id}")
            if [ "$s1" -eq 200 ]; then
              n="$(_extract_name_from_json comp.json)"
            fi
          fi

          # 3) Try org-scoped component endpoint if org_id provided and still no name
          local s2="0"
          if [ -z "${n:-}" ] && [ -n "${ORG_ID:-}" ]; then
            s2=$(curl -s -w "%{http_code}" -o comp_org.json \
              -H "Authorization: Bearer $CB_PAT" \
              -H "Accept: application/json" \
              "$CB_API_URL/v3/organizations/${ORG_ID}/components/${_id}")
            if [ "$s2" -eq 200 ]; then
              n="$(_extract_name_from_json comp_org.json)"
            fi
          fi

          # If still empty, record a soft note and fallback to the UUID
          if [ -z "${n:-}" ]; then
            jq --arg id "$_id" --arg s1 "$s1" --arg s2 "$s2" \
              '.errors += [{"component_id": $id, "status": 200, "message": ("Name lookup fell back to ID (HTTPs: /components=" + $s1 + ", /orgs/components=" + ( $s2 // "0" ) + ")")} ]' \
              errors.json > tmp.json && mv tmp.json errors.json
            n="$_id"
          fi

          printf "%s" "$n" > ".cache/${_id}.name"
          printf "%s" "$n"
        }

        for COMPONENT_ID in $(echo "$COMPONENT_IDS" | tr ',' ' '); do
          echo "📦 Fetching for component: $COMPONENT_ID"
          STATUS=$(curl -s -w "%{http_code}" -o response.json \
            -H "Authorization: Bearer $CB_PAT" \
            -H "Accept: application/json" \
            "$CB_API_URL/v3/components/$COMPONENT_ID/artifactinfos")

          COMPONENT_NAME="$(get_component_name "$COMPONENT_ID")"

          if [ "$STATUS" -ne 200 ]; then
            echo "❌ Component fetch failed for $COMPONENT_ID (HTTP $STATUS)"
            jq --arg id "$COMPONENT_ID" --arg name "$COMPONENT_NAME" --arg status "$STATUS" \
              '.errors += [{"component_id": $id, "component_name": $name, "status": ($status | tonumber), "message": "Component fetch failed"}]' \
              errors.json > tmp.json && mv tmp.json errors.json

            {
              echo "$COMPONENT_ID:"
              echo "  component_name: \"$COMPONENT_NAME\""
              echo "  matched: false"
              echo "  artifact_id: null"
              echo "  version: null"
              echo "  timestamp: null"
              echo "  artifact_name: null"
            } >> manifest.yaml
            continue
          fi

          MATCH=$(jq -r \
            ".artifacts // [] | .[] | select($FILTER) | \"\(.id) \(.version) \(.publishedOn) \(.name)\"" \
            response.json 2>/dev/null | head -n 1 || true)

          if [ -z "$MATCH" ]; then
            echo "⚠️  No matching artifact found for $COMPONENT_ID (labels: $LABELS)"
            {
              echo "$COMPONENT_ID:"
              echo "  component_name: \"$COMPONENT_NAME\""
              echo "  matched: false"
              echo "  artifact_id: null"
              echo "  version: null"
              echo "  timestamp: null"
              echo "  artifact_name: null"
            } >> manifest.yaml

            jq --arg id "$COMPONENT_ID" --arg name "$COMPONENT_NAME" --arg labels "$LABELS" \
              '.errors += [{"component_id": $id, "component_name": $name, "status": 200, "message": ("No artifact matched labels: " + $labels)}]' \
              errors.json > tmp.json && mv tmp.json errors.json
            continue
          fi

          ARTIFACT_ID=$(echo "$MATCH" | awk '{print $1}')
          VERSION=$(echo "$MATCH" | awk '{print $2}')
          TIMESTAMP=$(echo "$MATCH" | awk '{print $3}')
          ARTIFACT_NAME=$(echo "$MATCH" | cut -d' ' -f4-)

          {
            echo "$COMPONENT_ID:"
            echo "  component_name: \"$COMPONENT_NAME\""
            echo "  matched: true"
            echo "  artifact_id: \"$ARTIFACT_ID\""
            echo "  version: \"$VERSION\""
            echo "  timestamp: \"$TIMESTAMP\""
            echo "  artifact_name: \"$ARTIFACT_NAME\""
          } >> manifest.yaml
        done

        echo "✅ Final Manifest:"
        cat manifest.yaml
        echo "📋 Final Errors:"
        cat errors.json

        # Write outputs
        cat manifest.yaml > "$CLOUDBEES_OUTPUTS/manifest"
        cat errors.json > "$CLOUDBEES_OUTPUTS/errors"
