apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: generate-artifact-manifest
description: Generates a YAML manifest of latest artifacts for a list of components.

inputs:
  cb_api_url:
    required: true
  cb_pat:
    required: true
  component_ids:
    required: true
    description: Comma-separated list of component IDs (e.g. id1,id2)
  labels:
    required: true
    description: Label filters to apply (e.g. rel=squid-ui,ns=squid-prod)
  org_id:
    required: false
    description: Optional organization ID for org-scoped component lookups

outputs:
  manifest:
    description: YAML-formatted artifact manifest with IDs, versions, timestamps, artifact names, component names, and match status
    value: ${{ steps.generate.outputs.manifest }}
  errors:
    description: JSON-formatted list of components that failed to fetch or match (with name-lookup diagnostics)
    value: ${{ steps.generate.outputs.errors }}

runs:
  using: composite
  steps:
    - id: generate
      name: Generate artifact manifest
      uses: docker://python:3.11-alpine
      shell: sh
      env:
        CB_API_URL: ${{ inputs.cb_api_url }}
        CB_PAT: ${{ inputs.cb_pat }}
        COMPONENT_IDS: ${{ inputs.component_ids }}
        LABELS: ${{ inputs.labels }}
        ORG_ID: ${{ inputs.org_id }}
      run: |
        set -eu
        apk add --no-cache curl jq coreutils > /dev/null

        echo "🔍 Fetching latest artifacts for: $COMPONENT_IDS"
        : > manifest.yaml
        echo '{"errors":[]}' > errors.json
        mkdir -p .cache
        echo "🔍 Created blank manifest, error file, and cache dir"

        # Build a jq filter that tolerates missing labels
        FILTER=$(echo "$LABELS" | awk -F, '
          BEGIN { first=1 }
          {
            for (i = 1; i <= NF; i++) {
              if ($i == "") continue
              split($i, kv, "=")
              if (!first) { printf " and " }
              printf "(((.labels // []) | index(\"%s=%s\")))", kv[1], kv[2]
              first=0
            }
          }')

        if [ -z "$FILTER" ]; then
          echo "ℹ️  No labels provided after parsing; defaulting to match-any artifact"
          FILTER="true"
        fi

        echo "🔍 Filtering artifacts by labels: $LABELS"
        echo "🧮 Using jq filter: $FILTER"

        # Extract a plausible name from a JSON payload
        extract_name_from_json() {
          jq -r '
            .component.name
            // .component.displayName
            // .component.title
            // .name
            // .displayName
            // .title
            // .metadata.name
            // .data.name
            // empty
          ' "$1" 2>/dev/null || true
        }

        # Timed curl that returns "<code> <time_total_s>"
        timed_curl() {
          url="$1"
          out="$2"
          # Outputs two tokens: HTTP_CODE and time_total (seconds, may be fractional)
          curl -sS -o "$out" -w "%{http_code} %{time_total}" \
            -H "Authorization: Bearer $CB_PAT" \
            -H "Accept: application/json" \
            "$url"
        }

        # Name lookup with caching and multiple strategies.
        # get_component_name <id> <artifact_name_if_any>
        get_component_name() {
          _id="$1"
          _artifact_name="${2:-}"

          if [ -f ".cache/${_id}.name" ]; then
            cat ".cache/${_id}.name"
            return 0
          fi

          name=""

          # A) Try last artifactinfos body if present
          if [ -f response.json ]; then
            name="$(extract_name_from_json response.json)"
          fi

          # B) Org-scoped endpoint (if org provided and still no name)
          oc_code=""
          oc_time=""
          if [ -z "$name" ] && [ -n "${ORG_ID:-}" ]; then
            oc_result="$(timed_curl "$CB_API_URL/v3/organizations/${ORG_ID}/components/${_id}" comp_org.json)"
            oc_code=$(echo "$oc_result" | awk '{print $1}')
            oc_time=$(echo "$oc_result" | awk '{print $2}')
            if [ "$oc_code" = "200" ]; then
              name="$(extract_name_from_json comp_org.json)"
            fi
          fi

          # C) Global endpoint (if still no name)
          c_code=""
          c_time=""
          if [ -z "$name" ]; then
            c_result="$(timed_curl "$CB_API_URL/v3/components/${_id}" comp.json)"
            c_code=$(echo "$c_result" | awk '{print $1}')
            c_time=$(echo "$c_result" | awk '{print $2}')
            if [ "$c_code" = "200" ]; then
              name="$(extract_name_from_json comp.json)"
            fi
          fi

          # D) Heuristic from artifact_name (e.g., repo/image -> image)
          if [ -z "$name" ] && [ -n "$_artifact_name" ]; then
            name=$(echo "$_artifact_name" | awk -F'/' '{print $NF}')
          fi

          # E) Fallback to UUID and record diagnostics
          if [ -z "$name" ]; then
            name="$_id"
            jq --arg id "$_id" \
               --arg oc_code "${oc_code:-0}" --arg oc_time "${oc_time:-0}" \
               --arg c_code  "${c_code:-0}"  --arg c_time  "${c_time:-0}" \
               '.errors += [{
                  "component_id": $id,
                  "status": 200,
                  "message": "Name lookup fell back to ID",
                  "lookup_attempts": {
                    "org_components": { "status": ($oc_code|tonumber? // 0), "time_s": ($oc_time|tonumber? // 0) },
                    "components":     { "status": ($c_code|tonumber?  // 0), "time_s": ($c_time|tonumber?  // 0) }
                  }
                }]' \
                errors.json > tmp.json && mv tmp.json errors.json
          fi

          printf "%s" "$name" > ".cache/${_id}.name"
          printf "%s" "$name"
        }

        # Main loop
        for COMPONENT_ID in $(echo "$COMPONENT_IDS" | tr ',' ' '); do
          echo "📦 Fetching for component: $COMPONENT_ID"

          ai_result="$(timed_curl "$CB_API_URL/v3/components/$COMPONENT_ID/artifactinfos" response.json)"
          ai_code=$(echo "$ai_result" | awk '{print $1}')
          ai_time=$(echo "$ai_result" | awk '{print $2}')
          echo "⏱️  artifactinfos: status=$ai_code time_s=$ai_time"

          if [ "$ai_code" != "200" ]; then
            cname="$(get_component_name "$COMPONENT_ID")"
            echo "❌ Component fetch failed for $COMPONENT_ID (HTTP $ai_code, ${ai_time}s)"
            jq --arg id "$COMPONENT_ID" --arg name "$cname" --arg code "$ai_code" --arg t "$ai_time" \
              '.errors += [{"component_id": $id, "component_name": $name, "status": ($code | tonumber), "message": ("Component fetch failed; time_s=" + $t)}]' \
              errors.json > tmp.json && mv tmp.json errors.json

            {
              echo "$COMPONENT_ID:"
              echo "  component_name: \"$cname\""
              echo "  matched: false"
              echo "  artifact_id: null"
              echo "  version: null"
              echo "  timestamp: null"
              echo "  artifact_name: null"
            } >> manifest.yaml
            continue
          fi

          MATCH=$(jq -r ".artifacts // [] | .[] | select($FILTER) | \"\(.id) \(.version) \(.publishedOn) \(.name)\"" response.json 2>/dev/null | head -n 1 || true)

          ARTIFACT_NAME=""
          if [ -n "$MATCH" ]; then
            ARTIFACT_NAME=$(echo "$MATCH" | cut -d' ' -f4-)
          fi

          COMPONENT_NAME="$(get_component_name "$COMPONENT_ID" "$ARTIFACT_NAME")"

          if [ -z "$MATCH" ]; then
            echo "⚠️  No matching artifact found for $COMPONENT_ID (labels: $LABELS)"
            {
              echo "$COMPONENT_ID:"
              echo "  component_name: \"$COMPONENT_NAME\""
              echo "  matched: false"
              echo "  artifact_id: null"
              echo "  version: null"
              echo "  timestamp: null"
              echo "  artifact_name: null"
            } >> manifest.yaml

            jq --arg id "$COMPONENT_ID" --arg name "$COMPONENT_NAME" --arg labels "$LABELS" \
              '.errors += [{"component_id": $id, "component_name": $name, "status": 200, "message": ("No artifact matched labels: " + $labels)}]' \
              errors.json > tmp.json && mv tmp.json errors.json
            continue
          fi

          ARTIFACT_ID=$(echo "$MATCH" | awk '{print $1}')
          VERSION=$(echo "$MATCH" | awk '{print $2}')
          TIMESTAMP=$(echo "$MATCH" | awk '{print $3}')

          {
            echo "$COMPONENT_ID:"
            echo "  component_name: \"$COMPONENT_NAME\""
            echo "  matched: true"
            echo "  artifact_id: \"$ARTIFACT_ID\""
            echo "  version: \"$VERSION\""
            echo "  timestamp: \"$TIMESTAMP\""
            echo "  artifact_name: \"$ARTIFACT_NAME\""
          } >> manifest.yaml
        done

        # Final prints (don’t fail if cat has issues)
        set +e
        echo "✅ Final Manifest:"
        cat manifest.yaml
        echo "📋 Final Errors:"
        cat errors.json
        set -e

        # Outputs
        cat manifest.yaml > "$CLOUDBEES_OUTPUTS/manifest"
        cat errors.json > "$CLOUDBEES_OUTPUTS/errors"
